{% set version = "4.4.11" %}

package:
  name: dssp
  version: {{ version }}

source:
  url: https://github.com/PDB-REDO/dssp/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 49dd6560358ba65fb971e158f78a54557ab6da1c49e502704b3bb9518e17acce

build:
  number: 1
  script:
    - >
      cmake -S . -B build
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_INSTALL_PREFIX={{ PREFIX }}
      -DCMAKE_FIND_FRAMEWORK=NEVER
      -DCMAKE_FIND_APPBUNDLE=NEVER
      -DCMAKE_CXX_COMPILER=${CXX}
      -DCMAKE_CXX_FLAGS="-D_LIBCPP_DISABLE_AVAILABILITY"  # [osx]
      ${CMAKE_ARGS}
    - cmake --build build --config Release
    - cmake --install build

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - make
  host:
    - zlib

test:
  commands:
    - mkdssp 1aki.cif 1aki_dssp.cif
  files:
    - 1aki.cif

about:
  home: https://github.com/PDB-REDO/dssp
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Application to assign secondary structure to proteins
  doc_url: https://pdb-redo.eu/dssp
  dev_url: https://github.com/PDB-REDO/dssp

extra:
  recipe-maintainers:
    - padix-key
    - mhekkel
